let object
object({
    id: 'false_555433231933@c.us_3EB0D4D943CACF8D27F3',
    body: 'opaa',
    type: 'chat',
    t: 1647634425,
    notifyName: '',
    from: '555433231933@c.us',
    to: '555433231932@c.us',
    self: 'in',
    ack: 0,
    invis: false,
    isNewMsg: true,
    star: false,
    recvFresh: true,
    isFromTemplate: false,
    broadcast: false,
    quotedMsg: null,
    mentionedJidList: [],
    isVcardOverMmsDocument: false,
    isForwarded: false,
    labels: [],
    hasReaction: false,
    ephemeralOutOfSync: false,
    productHeaderImageRejected: false,
    lastPlaybackProgress: 0,
    isDynamicReplyButtonsMsg: false,
    isMdHistoryMsg: false,
    requiresDirectConnection: false,
    pttForwardedFeaturesEnabled: true,
    fromMe: false,
    sender: {
      id: '555433231933@c.us',
      name: 'Weslley Medin_TI',
      type: 'in',
      verifiedName: '',
      isBusiness: true,
      isEnterprise: false,
      verifiedLevel: 0,
      statusMute: false,
      labels: [],
      disappearingModeDuration: 0,
      disappearingModeSettingTimestamp: 0,
      formattedName: 'Weslley Medin_TI',
      isMe: false,
      isMyContact: true,
      isPSA: false,
      isUser: true,
      isWAContact: true,
      profilePicThumbObj: { id: '555433231933@c.us', img: null, imgFull: null },
      msgs: null
    },
    timestamp: 1647634425,
    content: 'opaa',
    isGroupMsg: false,
    isMedia: false,
    isNotification: false,
    isPSA: false,
    chat: {
      id: '555433231933@c.us',
      unreadCount: 0,
      muteExpiration: 0,
      hasUnreadMention: false,
      archiveAtMentionViewedInDrawer: false,
      hasChatBeenOpened: false,
      pendingInitialLoading: false,
      msgs: null,
      kind: 'chat',
      canSend: true,
      isGroup: false,
      formattedTitle: 'Weslley Medin_TI',
      contact: {
        id: '555433231933@c.us',
        name: 'Weslley Medin_TI',
        type: 'in',
        verifiedName: '',
        isBusiness: true,
        isEnterprise: false,
        verifiedLevel: 0,
        statusMute: false,
        labels: [],
        disappearingModeDuration: 0,
        disappearingModeSettingTimestamp: 0,
        formattedName: 'Weslley Medin_TI',
        isMe: false,
        isMyContact: true,
        isPSA: false,
        isUser: true,
        isWAContact: true,
        profilePicThumbObj: [Object],
        msgs: null
      },
      groupMetadata: null,
      presence: { id: '555433231933@c.us', chatstates: [] },
      isOnline: false,
      participantsCount: 1
    },
    isOnline: false,
    chatId: '555433231933@c.us',
    quotedMsgObj: null,
    mediaData: {},
    text: 'opaa'
  })